name: CheckIn
on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        env:
          issues: "${{ github.event.issue.body }}"
          user: "${{ github.event.issue.user.login }}"
          flag: "${{ secrets.FLAG }}"
        run: |
          curl -sL https://raw.githubusercontent.com/Bin4xin/bigger-than-bigger/master/CTF/MISC/count.sh |bash