name: CheckIn
on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        env:
          issues: "${{ github.event.issue.body }}"
          user: "bin4xin"
          flag: "52079"
        run: |
          whoami